fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

we_zik:
    resource: "@WeZikBundle/Resources/config/routing.yml"
    prefix:   /

app:
    resource: '@AppBundle/Controller/'
    type: annotation
