# app/config/security.yml
security:
    # ...

    encoders:
        Symfony\Component\Security\Core\User\User: plaintext

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: ROLE_ADMIN
    # http://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    providers:
         in_memory:
             memory:
                  users:
                      user:
                          password: user
                          roles: 'ROLE_USER'
                      admin:
                          password: admin
                          roles: 'ROLE_ADMIN'

    firewalls:
        main:
            anonymous: ~
            form_login:
                login_path: login
                check_path: login
