<?php

namespace WeZikBundle\Repository;

/**
 * MorceauRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MorceauRepository extends \Doctrine\ORM\EntityRepository
{
}
