we_zik_homepage:
    path:     /
    defaults: { _controller: WeZikBundle:Default:index }

login:
    path:     /login
    defaults: { _controller: WeZikBundle:Security:login }

info:
    path:     /info
    defaults: { _controller: WeZikBundle:Security:login }

generate_user:
    path:     /user
    defaults: { _controller: WeZikBundle:Default:userToJSON }

generate_morceau:
    path:     /morceau
    defaults: { _controller: WeZikBundle:Default:morceauToJSON }

generate_tag:
    path:     /tag
    defaults: { _controller: WeZikBundle:Default:tagToJSON }

generate_playlist:
    path:     /playlist
    defaults: { _controller: WeZikBundle:Default:playlistToJSON }

addToPlaylist:
    path:     /add/{id_playlist}/{id_morceau}
    defaults: { _controller: WeZikBundle:Default:addToPlaylist }

retireFromPlaylist:
    path:     /delete/{id_playlist}/{id_morceau}
    defaults: { _controller: WeZikBundle:Default:retireFromPlaylist }

playJSON:
    path:     /play/{id_playlist}
    defaults: { _controller: WeZikBundle:Default:playJSON }

showUser:
    path:     /profile/{id_user}
    defaults: { _controller: WeZikBundle:Default:showUser }

showTag:
    path:     /tags/{id_tag}
    defaults: { _controller: WeZikBundle:Default:showTag }

test123:
    path:     /test
    defaults: { _controller: WeZikBundle:Default:testReturn123 }

getPlaylist:
    path:     /get/playlist/{id_playlist}
    defaults: { _controller: WeZikBundle:Default:getPlaylist }

getAllPlaylists:
    path:     /get/playlists
    defaults: { _controller: WeZikBundle:Default:getAllPlaylists }

getTaglist:
    path:     /get/tag/{id_taglist}
    defaults: { _controller: WeZikBundle:Default:getTaglist }

getAllTaglists:
    path:     /get/taglists
    defaults: { _controller: WeZikBundle:Default:getAllTaglists }

getMorceau:
    path:     /get/morceau/{id_morceau}
    defaults: { _controller: WeZikBundle:Default:getMorceau }

getAllMorceaux:
    path:     /get/morceaux
    defaults: { _controller: WeZikBundle:Default:getAllMorceaux }

getUser:
    path:     /get/user/{id_user}
    defaults: { _controller: WeZikBundle:Default:getUser }

getAllUsers:
    path:     /get/users
    defaults: { _controller: WeZikBundle:Default:getAllUsers }

generateFakeMorceau:
    path:     /generateM/{titre}/{url}
    defaults: { _controller: WeZikBundle:Default:generateFake }