we_zik_homepage:
    path:     /
    defaults: { _controller: WeZikBundle:Default:index }

generate_user:
    path:     /userG
    defaults: { _controller: WeZikBundle:Default:userToJSON }

generate_morceau:
    path:     /morceauG
    defaults: { _controller: WeZikBundle:Default:morceauToJSON }

generate_playlist:
    path:     /playlistG
    defaults: { _controller: WeZikBundle:Default:playlistToJSON }

generate_tag:
    path:     /tagG
    defaults: { _controller: WeZikBundle:Default:tagToJSON }

