we_zik_homepage:
    path:     /
    defaults: { _controller: WeZikBundle:Default:index }

generate_user:
    path:     /user
    defaults: { _controller: WeZikBundle:Default:userToJSON }

generate_morceau:
    path:     /morceau
    defaults: { _controller: WeZikBundle:Default:morceauToJSON }

generate_tag:
    path:     /tag
    defaults: { _controller: WeZikBundle:Default:tagToJSON }

generate_playlist:
    path:     /playlist
    defaults: { _controller: WeZikBundle:Default:playlistToJSON }

addToPlaylist:
    path:     /add/{id_playlist}/{id_morceau}
    defaults: { _controller: WeZikBundle:Default:addToPlaylist }

retireFromPlaylist:
    path:     /delete/{id_playlist}/{id_morceau}
    defaults: { _controller: WeZikBundle:Default:retireFromPlaylist }

playJSON:
    path:     /play/{id_playlist}
    defaults: { _controller: WeZikBundle:Default:playJSON }

showUser:
    path:     /profile/{id_user}
    defaults: { _controller: WeZikBundle:Default:showUser }

showTag:
    path:     /tags/{id_tag}
    defaults: { _controller: WeZikBundle:Default:showTag }

test123:
    path:     /test
    defaults: { _controller: WeZikBundle:Default:testReturn123 }

getPlaylistAction:
    path:     /get/playlist/{id_playlist}
    defaults: { _controller: WeZikBundle:Default:getPlaylist }

getAllPlaylistsAction:
    path:     /get/playlists
    defaults: { _controller: WeZikBundle:Default:getAllPlaylists }
