we_zik_homepage:
    path:     /
    defaults: { _controller: WeZikBundle:Default:index }

generate_user:
    path:     /userG
    defaults: { _controller: WeZikBundle:Default:userToJSON }

generate_morceau:
    path:     /morceauG
    defaults: { _controller: WeZikBundle:Default:morceauToJSON }

generate_playlist:
    path:     /playlistG
    defaults: { _controller: WeZikBundle:Default:playlistToJSON }

addToPlaylist:
    path:     /add/{id_morceau}/{id_playlist}
    defaults: { _controller: WeZikBundle:Default:addToPlaylist }

retireFromPlaylist:
    path:     /delete/{id_morceau}/{id_playlist}
    defaults: { _controller: WeZikBundle:Default:retireFromPlaylist }

playJSON:
    path:     /play/{id_morceau}/{id_playlist}
    defaults: { _controller: WeZikBundle:Default:playJSON }

showUser:
    path:     /profile/{id_user}
    defaults: { _controller: WeZikBundle:Default:showUser }

showTag:
    path:     /tags/{id_tag}
    defaults: { _controller: WeZikBundle:Default:showTag }